# -*- coding: utf-8 -*-
"""Registro curado a mano de la geografia industrial basal argentina.

Fuente unica: ``scripts/industria/Geografia_Industrial_Argentina.md``.

Cada elemento de ``REGISTROS`` es un dict que representa UN nodo productivo
(planta, cantera, puerto, central o polo regional). Las filas agrupadas del
documento fueron desagregadas: "Plantas Pilar, Chacabuco, San Justo, Tres
Arroyos, Pigue" produce cinco registros, "Rosario y Capital (Santa Fe)" dos,
etc.

Exclusiones deliberadas (no son nodos productivos o estan fuera de alcance):
  * Centros de distribucion de Grupo Calidra (Rosario, Cordoba, Campana,
    Resistencia, Santiago de Chile) -- sin produccion.
  * Sucursales comerciales de IMSA (Rosario, Santa Fe, Cordoba) -- sin produccion.
  * Operacion de IMSA/Neorol en Montevideo, Uruguay -- fuera de Argentina.
  * "Molino harinero historico La Clara" -- el propio documento lo marca fuera
    de alcance.
  * "Ilva" -- marca comercial de Ceramica San Lorenzo, no una planta.
  * Fila resumen "Vulcano, Randon, Helvetica, Cometto, Sola y Brusa" de la
    seccion 6 -- remite al desglose 6.bis, que si esta cargado.
  * "Ex plantas Morteros y Chivilcoy" de SanCor -- esas plantas ya figuran
    como registros de Adecoagro.

Campos del dict
---------------
id                    Identificador estable: IND-<COD>-<NNN>, secuencia en
                      orden de aparicion en el documento.
empresa               Razon social / grupo controlante.
planta                Nombre de la planta o complejo.
categoria             Una de las 8 categorias canonicas (ver CATEGORIAS).
categoria_cod         Codigo de 3 letras de la categoria.
subsector             Sub-rubro fino (Cemento, Cal, Yeso, Hormigon, Acero
                      plano, Aluminio, Lacteos, Molineria, Remolques, ...).
tipo                  PLANTA | POLO_REGIONAL | CANTERA | PUERTO | CENTRAL_ENERGETICA
producto_principal    Producto declarado en el documento.
capacidad_declarada   Capacidad tal como la declara el documento; "Sin dato
                      publico oficial" cuando el documento dice "s/d" o "-".
origen_materia_prima  Idem, con el mismo relleno por defecto.
estado_operativo      ACTIVA | CERRADA | EN_QUIEBRA/SUBASTA
ubicacion_texto       Ubicacion textual verbatim del documento.
localidad             Localidad normalizada usada para validar el geocoding.
provincia             Provincia normalizada usada para validar el geocoding.
notas                 Observaciones del curador (opcional).
sin_ubicar            True cuando el documento no da un lugar localizable.
geocode               Lista ordenada de consultas candidatas a Nominatim. Gana
                      la primera que sea aceptada. Cada candidato es
                      {"q": consulta, "precision": "EXACTA"|"ESTIMADA",
                       "solo_feature": bool}. ``solo_feature`` marca las
                      consultas por nombre de empresa/planta: si Nominatim
                      devuelve el centroide de la ciudad en vez de un rasgo
                      real (landuse=industrial, man_made=works, etc.) el
                      candidato se descarta y se pasa al siguiente.
"""

from __future__ import annotations

CATEGORIAS: dict[str, str] = {
    "CEM": "Cemento, Cal y Yeso",
    "SID": "Siderurgia, Metalurgia y Perfilería",
    "ARI": "Áridos, Cerámica Roja y Pisos",
    "VID": "Vidrio y Aislaciones",
    "HID": "Infraestructura Hídrica y Polímeros de Conducción",
    "MAQ": "Maquinaria Pesada, Agrícola, Vial y Carrocerías",
    "MOL": "Molinería y Alimentos Básicos a Granel",
    "ENE": "Nodos Energéticos y Material Eléctrico Pesado",
}

# Slug de archivo por categoria (datasets/industria/industria_<slug>.geojson)
CATEGORIA_SLUG: dict[str, str] = {
    "CEM": "cemento_cal_yeso",
    "SID": "siderurgia",
    "ARI": "aridos_ceramica",
    "VID": "vidrio_aislaciones",
    "HID": "hidrica_polimeros",
    "MAQ": "maquinaria",
    "MOL": "molineria_alimentos",
    "ENE": "energia_electrico",
}

SIN_DATO = "Sin dato público oficial"


# --------------------------------------------------------------------------
# Helpers de construccion (mantienen el registro legible sin perder campos)
# --------------------------------------------------------------------------

def _ef(q: str) -> dict:
    """Candidato EXACTA por nombre de empresa/planta (exige rasgo real)."""
    return {"q": q, "precision": "EXACTA", "solo_feature": True}


def _e(q: str) -> dict:
    """Candidato EXACTA por direccion, parque industrial, paraje o villa."""
    return {"q": q, "precision": "EXACTA", "solo_feature": False}


def _a(q: str) -> dict:
    """Candidato ESTIMADA: centroide de localidad."""
    return {"q": q, "precision": "ESTIMADA", "solo_feature": False}


def _r(
    id: str,
    empresa: str,
    planta: str,
    categoria_cod: str,
    subsector: str,
    producto_principal: str,
    capacidad_declarada: str,
    origen_materia_prima: str,
    ubicacion_texto: str,
    localidad: str,
    provincia: str,
    geocode: list,
    tipo: str = "PLANTA",
    estado_operativo: str = "ACTIVA",
    notas: str = "",
    sin_ubicar: bool = False,
) -> dict:
    return {
        "id": id,
        "empresa": empresa,
        "planta": planta,
        "categoria": CATEGORIAS[categoria_cod],
        "categoria_cod": categoria_cod,
        "subsector": subsector,
        "tipo": tipo,
        "producto_principal": producto_principal,
        "capacidad_declarada": capacidad_declarada or SIN_DATO,
        "origen_materia_prima": origen_materia_prima or SIN_DATO,
        "estado_operativo": estado_operativo,
        "ubicacion_texto": ubicacion_texto,
        "localidad": localidad,
        "provincia": provincia,
        "notas": notas,
        "sin_ubicar": sin_ubicar,
        "geocode": geocode,
    }


REGISTROS: list[dict] = [

    # =====================================================================
    # 1. CEMENTO, CAL Y YESO  (CEM)
    # =====================================================================

    # --- 1.1 Cemento - Loma Negra (Grupo InterCement) --------------------
    _r("IND-CEM-001", "Loma Negra CIASA (Grupo InterCement)", "L'Amalí (I y II)",
       "CEM", "Cemento", "Clinker y cemento portland",
       "Línea 2 (\"L'Amalí II\", 2021, US$350M) sumó ~25% a la producción nacional de la empresa",
       "Caliza de canteras propias en Olavarría (Sierras de Tandilia)",
       "Camino Real s/n, Villa Alfredo Fortabat, Olavarría, Bs. As.",
       "Olavarría", "Buenos Aires",
       [_ef("L'Amalí, Olavarría, Buenos Aires, Argentina"),
        _ef("Loma Negra L'Amalí, Olavarría, Buenos Aires, Argentina"),
        _e("Villa Alfredo Fortabat, Olavarría, Buenos Aires, Argentina"),
        _e("Loma Negra, Partido de Olavarría, Buenos Aires, Argentina"),
        _a("Olavarría, Buenos Aires, Argentina")],
       notas="Planta de clinker más grande del país tras la ampliación de 2021."),

    _r("IND-CEM-002", "Loma Negra CIASA (Grupo InterCement)", "Planta Barker",
       "CEM", "Cemento", "Cemento portland", "", "Caliza local",
       "Est. Alfredo Fortabat (e/Barker y Loma Negra), Benito Juárez, Bs. As.",
       "Barker", "Buenos Aires",
       [_ef("Loma Negra, Barker, Benito Juárez, Buenos Aires, Argentina"),
        _e("Barker, Benito Juárez, Buenos Aires, Argentina"),
        _a("Benito Juárez, Buenos Aires, Argentina")]),

    _r("IND-CEM-003", "Loma Negra CIASA (Grupo InterCement)",
       "Planta Ramallo (molienda con escoria \"Ecocemento\")",
       "CEM", "Cemento", "Molienda de cemento (clinker + escoria de alto horno)",
       "", "Clinker propio + escoria de Ternium San Nicolás",
       "Ing. Agustín Roca 315, Parque Industrial Comirsa, Ramallo, Bs. As.",
       "Ramallo", "Buenos Aires",
       [_ef("Loma Negra, Ramallo, Buenos Aires, Argentina"),
        _e("Comirsa, Ramallo, Buenos Aires, Argentina"),
        _e("Parque Industrial Comirsa, Ramallo, Buenos Aires, Argentina"),
        _e("Villa General Savio, Ramallo, Buenos Aires, Argentina"),
        _a("Ramallo, Buenos Aires, Argentina")],
       notas="Simbiosis industrial con Ternium San Nicolás (escoria de alto horno)."),

    _r("IND-CEM-004", "Loma Negra CIASA (Grupo InterCement)", "Planta Zapala",
       "CEM", "Cemento", "Cemento portland", "", "Caliza regional",
       "Av. Avellaneda y Coliqueo, Zapala, Neuquén",
       "Zapala", "Neuquén",
       [_ef("Loma Negra, Zapala, Neuquén, Argentina"),
        _e("Avenida Avellaneda y Coliqueo, Zapala, Neuquén, Argentina"),
        _a("Zapala, Neuquén, Argentina")]),

    _r("IND-CEM-005", "Loma Negra CIASA (Grupo InterCement)", "Planta Catamarca",
       "CEM", "Cemento", "Cemento portland", "", "Caliza local",
       "Paraje La Calera, El Alto, Catamarca",
       "El Alto", "Catamarca",
       [_ef("Loma Negra, El Alto, Catamarca, Argentina"),
        _e("La Calera, El Alto, Catamarca, Argentina"),
        _a("El Alto, Catamarca, Argentina")]),

    _r("IND-CEM-006", "Loma Negra CIASA (Grupo InterCement)", "Planta San Juan",
       "CEM", "Cemento", "Cemento (molienda)", "", "",
       "Ruta Provincial 12, Rivadavia, San Juan",
       "Rivadavia", "San Juan",
       [_ef("Loma Negra, Rivadavia, San Juan, Argentina"),
        _a("Rivadavia, San Juan, Argentina")]),

    _r("IND-CEM-007", "Loma Negra CIASA (Grupo InterCement)", "Planta Sierras Bayas",
       "CEM", "Cemento", "Ex-molienda y embolsado (primera planta del país, 1919)",
       "Cerrada — 0", "",
       "Sierras Bayas, Olavarría, Bs. As.",
       "Sierras Bayas", "Buenos Aires",
       [_e("Sierras Bayas, Olavarría, Buenos Aires, Argentina"),
        _a("Olavarría, Buenos Aires, Argentina")],
       estado_operativo="CERRADA",
       notas="Cerrada en 2019. Primera planta de cemento del país (1919); valor patrimonial."),

    # --- 1.2 Cemento - Holcim Argentina ---------------------------------
    _r("IND-CEM-008", "Holcim Argentina", "Malagueño (Centro Industrial Córdoba)",
       "CEM", "Cemento", "Clinker, cemento y morteros",
       "Ampliación 2021 (US$120M): +512.000 t/año clinker y +635.000 t/año cemento; planta de morteros Tector 120.000 t/año",
       "Caliza de Malagueño/Yocsina",
       "Malagueño, Depto. Santa María, Córdoba",
       "Malagueño", "Córdoba",
       [_ef("Holcim, Malagueño, Córdoba, Argentina"),
        _e("Malagueño, Córdoba, Argentina")]),

    _r("IND-CEM-009", "Holcim Argentina", "Planta Campana",
       "CEM", "Cemento", "Cemento (molienda)", "",
       "Clinker interno + insumos importados por puerto",
       "Ruta Nacional 9 km 81,5, Campana, Bs. As.",
       "Campana", "Buenos Aires",
       [_ef("Holcim, Campana, Buenos Aires, Argentina"),
        _a("Campana, Buenos Aires, Argentina")]),

    _r("IND-CEM-010", "Holcim Argentina", "Planta Puesto Viejo",
       "CEM", "Cemento", "Cemento", "", "Caliza local",
       "Ruta 53 s/n, Puesto Viejo, Jujuy",
       "Puesto Viejo", "Jujuy",
       [_ef("Holcim, Puesto Viejo, Jujuy, Argentina"),
        _e("Puesto Viejo, Jujuy, Argentina"),
        _a("El Carmen, Jujuy, Argentina")]),

    _r("IND-CEM-011", "Holcim Argentina", "Planta Capdeville",
       "CEM", "Cemento", "Cemento", "", "Caliza local",
       "Ruta Provincial 52 km 17,5, Capdeville, Las Heras, Mendoza",
       "Capdeville", "Mendoza",
       [_ef("Holcim, Capdeville, Las Heras, Mendoza, Argentina"),
        _e("Capdeville, Las Heras, Mendoza, Argentina"),
        _a("Las Heras, Mendoza, Argentina")]),

    _r("IND-CEM-012", "Holcim Argentina", "Ex planta Yocsina",
       "CEM", "Cemento", "Ex-molienda",
       "Cerrada, producción unificada en Malagueño", "",
       "Yocsina, Córdoba",
       "Yocsina", "Córdoba",
       [_e("Yocsina, Córdoba, Argentina"),
        _a("Malagueño, Córdoba, Argentina")],
       estado_operativo="CERRADA", notas="Cerrada en 2021."),

    # --- 1.3 Cemento - Cementos Avellaneda ------------------------------
    _r("IND-CEM-013", "Cementos Avellaneda S.A. (Cementos Molins / Votorantim)",
       "Planta Olavarría (San Jacinto)",
       "CEM", "Cemento", "Clinker y cemento",
       "Ampliación de línea en curso (obra IMPO en Parque Industrial Olavarría II)",
       "Caliza Sierras de Tandilia",
       "Paraje San Jacinto, Olavarría, Bs. As. (inicio 1937)",
       "Olavarría", "Buenos Aires",
       [_ef("Cementos Avellaneda, Olavarría, Buenos Aires, Argentina"),
        _e("San Jacinto, Olavarría, Buenos Aires, Argentina"),
        _a("Olavarría, Buenos Aires, Argentina")]),

    _r("IND-CEM-014", "Cementos Avellaneda S.A. (Cementos Molins / Votorantim)",
       "Planta San Luis (La Calera)",
       "CEM", "Cemento", "Cemento", "", "Caliza local",
       "La Calera, Depto. Belgrano, San Luis (inicio 1975)",
       "La Calera", "San Luis",
       [_ef("Cementos Avellaneda, La Calera, San Luis, Argentina"),
        _e("La Calera, San Luis, Argentina"),
        _a("Departamento Belgrano, San Luis, Argentina")]),

    _r("IND-CEM-015", "Cementos Avellaneda S.A. (Cementos Molins / Votorantim)",
       "Planta hormigones San Justo",
       "CEM", "Hormigón", "Hormigón elaborado", "", "Cemento propio",
       "Chenaut 435, Villa Luzuriaga, Bs. As.",
       "Villa Luzuriaga", "Buenos Aires",
       [_e("Chenaut 435, Villa Luzuriaga, Buenos Aires, Argentina"),
        _a("Villa Luzuriaga, La Matanza, Buenos Aires, Argentina")]),

    _r("IND-CEM-016", "Cementos Avellaneda S.A. (Cementos Molins / Votorantim)",
       "Planta hormigones Laferrere",
       "CEM", "Hormigón", "Hormigón elaborado", "", "Cemento propio",
       "Monseñor López May 1245, Isidro Casanova, Bs. As.",
       "Isidro Casanova", "Buenos Aires",
       [_e("Monseñor López May 1245, Isidro Casanova, Buenos Aires, Argentina"),
        _a("Isidro Casanova, La Matanza, Buenos Aires, Argentina")]),

    _r("IND-CEM-017", "Cementos Avellaneda S.A. (Cementos Molins / Votorantim)",
       "Planta hormigones José León Suárez",
       "CEM", "Hormigón", "Hormigón elaborado", "", "Cemento propio",
       "Camino Parque Buen Ayre y Bajada Debenedetti, José León Suárez, Bs. As.",
       "José León Suárez", "Buenos Aires",
       [_e("Camino del Buen Ayre, José León Suárez, Buenos Aires, Argentina"),
        _a("José León Suárez, General San Martín, Buenos Aires, Argentina")]),

    _r("IND-CEM-018", "Cementos Avellaneda S.A. (Cementos Molins / Votorantim)",
       "Planta hormigones Campana",
       "CEM", "Hormigón", "Hormigón elaborado", "", "Cemento propio",
       "Camino a Capilla del Señor 10, Campana, Bs. As.",
       "Campana", "Buenos Aires",
       [_e("Camino a Capilla del Señor 10, Campana, Buenos Aires, Argentina"),
        _a("Campana, Buenos Aires, Argentina")]),

    # --- 1.4 Cemento - PCR ----------------------------------------------
    _r("IND-CEM-019", "PCR S.A. (Petroquímica Comodoro Rivadavia)", "Planta Pico Truncado",
       "CEM", "Cemento", "Clinker y cemento portland",
       "~480.000 t/año cemento; horno de clinker 2.000 t/día (proyectado a 4.000 t/día); molienda 60 t/h",
       "Caliza de yacimiento propio (reservas ~100 M t)",
       "Pico Truncado, Santa Cruz (predio de 50 ha; inaugurada 2008)",
       "Pico Truncado", "Santa Cruz",
       [_ef("PCR Cemento, Pico Truncado, Santa Cruz, Argentina"),
        _a("Pico Truncado, Santa Cruz, Argentina")]),

    _r("IND-CEM-020", "PCR S.A. (Petroquímica Comodoro Rivadavia)", "Planta Comodoro Rivadavia",
       "CEM", "Cemento", "Molienda de cemento y despacho", "",
       "Clinker desde Pico Truncado",
       "Comodoro Rivadavia, Chubut",
       "Comodoro Rivadavia", "Chubut",
       [_ef("PCR, Comodoro Rivadavia, Chubut, Argentina"),
        _a("Comodoro Rivadavia, Chubut, Argentina")]),

    # --- 1.5 Cal industrial ---------------------------------------------
    _r("IND-CEM-021", "Caleras San Juan S.A.",
       "Planta Cienaguita (4 hornos MAERZ)",
       "CEM", "Cal",
       "Cal viva (siderurgia, minería del cobre/litio, construcción)",
       "600.000 t/año (tras 4° horno, 2025); horno 3 individual: 120.000 t/año",
       "Caliza de Los Berros/Cienaguita",
       "Cienaguita, Depto. Sarmiento, San Juan",
       "Cienaguita", "San Juan",
       [_ef("Caleras San Juan, Cienaguita, San Juan, Argentina"),
        _e("Cienaguita, Sarmiento, San Juan, Argentina"),
        _a("Los Berros, Sarmiento, San Juan, Argentina")],
       notas="Capitales 100% argentinos. Plan Maestro 2016-2025."),

    _r("IND-CEM-022", "Sibelco Argentina (grupo belga, ex Minera TEA)",
       "Planta Albardón (La Laja) — \"Minera Tea\"",
       "CEM", "Cal",
       "Cal para siderurgia, minería y construcción; sílice para vidrio/cerámica",
       "600.000 t/año, en ampliación a 760.000 t/año (1ª etapa) y proyectado a 920.000 t/año (inversión total US$100M)",
       "Caliza de Villicum/La Laja",
       "La Laja, Depto. Albardón, San Juan",
       "La Laja", "San Juan",
       [_ef("Sibelco, La Laja, Albardón, San Juan, Argentina"),
        _e("La Laja, Albardón, San Juan, Argentina"),
        _a("Albardón, San Juan, Argentina")]),

    _r("IND-CEM-023", "Sibelco Argentina (grupo belga)",
       "Planta Los Berros (ex La Buena Esperanza)",
       "CEM", "Cal", "Cal",
       "Incluida en capacidad consolidada de Sibelco San Juan", "Caliza local",
       "Los Berros, Depto. Sarmiento, San Juan",
       "Los Berros", "San Juan",
       [_ef("Sibelco, Los Berros, San Juan, Argentina"),
        _e("Los Berros, Sarmiento, San Juan, Argentina")]),

    _r("IND-CEM-024", "Sibelco Argentina (grupo belga)",
       "Planta El Villicum (ex El Volcán)",
       "CEM", "Cal", "Cal",
       "Incluida en capacidad consolidada de Sibelco San Juan", "Caliza local",
       "El Villicum, Depto. Albardón, San Juan",
       "El Villicum", "San Juan",
       [_e("El Villicum, Albardón, San Juan, Argentina"),
        _a("Albardón, San Juan, Argentina")]),

    _r("IND-CEM-025", "Grupo Calidra / CEFAS (mexicano)",
       "Planta Los Berros (marca \"El Milagro\")",
       "CEM", "Cal", "Cal viva y cal hidratada (marcas El Milagro, Sublime, Santa Elena)",
       "~200.000 t/año (previo a duplicación proyectada a 2019)", "Caliza local",
       "Los Berros, Depto. Sarmiento, San Juan",
       "Los Berros", "San Juan",
       [_ef("CEFAS, Los Berros, San Juan, Argentina"),
        _e("Los Berros, Sarmiento, San Juan, Argentina")]),

    _r("IND-CEM-026", "Compañía Minera del Pacífico S.A. (Cementos Bío Bío + Soprocal)",
       "Planta Jáchal (ex \"El Refugio\")",
       "CEM", "Cal", "Cal", "Parte del total provincial", "Caliza local",
       "Jáchal, San Juan",
       "San José de Jáchal", "San Juan",
       [_a("San José de Jáchal, San Juan, Argentina")],
       notas="Capitales chilenos. El documento no precisa el paraje de la planta."),

    _r("IND-CEM-027", "Grupo Calidra / CEFAS (mexicano)", "Planta Quilpo",
       "CEM", "Cal", "Ex-cal hidráulica (marcas Lougas y Feitis)",
       "Cerrada — operación cesada en 2017",
       "Caliza local (yacimiento agotado/discontinuado)",
       "Canteras Quilpo, 28 km de Cruz del Eje, Córdoba",
       "Cruz del Eje", "Córdoba",
       [_e("Quilpo, Cruz del Eje, Córdoba, Argentina"),
        _a("Cruz del Eje, Córdoba, Argentina")],
       estado_operativo="CERRADA"),

    _r("IND-CEM-028", "Grupo Calidra / CEFAS (mexicano)",
       "Planta Malagueño (\"Cal Malagueño\")",
       "CEM", "Cal", "Cal aérea hidratada para revoques y mampostería",
       "Incluida en capacidad consolidada de Calidra Cono Sur",
       "Caliza de las Sierras Chicas",
       "Malagueño, Córdoba",
       "Malagueño", "Córdoba",
       [_ef("Cal Malagueño, Malagueño, Córdoba, Argentina"),
        _e("Malagueño, Córdoba, Argentina")]),

    _r("IND-CEM-029", "Grupo Calidra / CEFAS (mexicano)", "Planta Olavarría",
       "CEM", "Cal", "Cal (marca \"Malagueño\" y otras)",
       "Incluida en capacidad consolidada de Calidra Cono Sur (>920.000 t/año junto con Albardón, Quilpo histórico, Olavarría y Zapala)",
       "Caliza de Tandilia",
       "Olavarría, Bs. As.",
       "Olavarría", "Buenos Aires",
       [_a("Olavarría, Buenos Aires, Argentina")]),

    _r("IND-CEM-030", "Grupo Calidra / CEFAS (mexicano)", "Planta Zapala",
       "CEM", "Cal", "Cal",
       "Incluida en capacidad consolidada de Calidra Cono Sur", "Caliza local",
       "Zapala, Neuquén",
       "Zapala", "Neuquén",
       [_a("Zapala, Neuquén, Argentina")]),

    # --- 1.6 Yeso --------------------------------------------------------
    _r("IND-CEM-031", "Knauf Argentina", "Planta Luján de Cuyo",
       "CEM", "Yeso",
       "Placas de yeso, perfiles de acero galvanizado y masilla",
       "Mayor capacidad productiva de placas de yeso y masillas en polvo de Sudamérica (cifra propia no desagregada)",
       "Yeso de canteras cuyanas",
       "Luján de Cuyo, Mendoza",
       "Luján de Cuyo", "Mendoza",
       [_ef("Knauf, Luján de Cuyo, Mendoza, Argentina"),
        _a("Distrito Ciudad de Luján de Cuyo, Mendoza, Argentina")],
       notas="Única planta del grupo Knauf en el país (2001)."),

    _r("IND-CEM-032", "Saint-Gobain Placo", "Planta Chimbas",
       "CEM", "Yeso", "Placas de yeso laminado (marcas Placo y Tuyango)",
       "", "Yeso de yacimientos sanjuaninos",
       "Chimbas, San Juan",
       "Chimbas", "San Juan",
       [_ef("Saint-Gobain, Chimbas, San Juan, Argentina"),
        _a("Chimbas, San Juan, Argentina")]),

    _r("IND-CEM-033", "Durlock S.A. (Grupo Etex, belga)",
       "Complejo industrial General Acha",
       "CEM", "Yeso", "Placas de yeso y masillas (sistema Durlock)",
       "24.000.000 m²/año (ampliada desde 7,5 M m²/año original tras inversión de US$19M en 1997)",
       "Yeso pampeano",
       "General Acha, La Pampa",
       "General Acha", "La Pampa",
       [_ef("Durlock, General Acha, La Pampa, Argentina"),
        _a("General Acha, La Pampa, Argentina")],
       notas="Planta fundacional (1977)."),

    _r("IND-CEM-034", "Durlock S.A. (Grupo Etex, belga)", "Plantas Malargüe (2 plantas)",
       "CEM", "Yeso",
       "Yesos tradicionales en polvo (Yemaco, Alpress, Aljez) y bloques macizos",
       "", "Yeso cuyano",
       "Malargüe, Mendoza",
       "Malargüe", "Mendoza",
       [_ef("Durlock, Malargüe, Mendoza, Argentina"),
        _a("Malargüe, Mendoza, Argentina")],
       notas="El documento consigna DOS plantas en Malargüe desde 1997; se georreferencian como un único nodo por falta de domicilios individuales."),

    _r("IND-CEM-035", "Durlock S.A. (ex \"Cía. Corral\", adquirida 2008)",
       "Planta General Roca — yesera histórica (barrio Stefenelli)",
       "CEM", "Yeso", "Yeso en bolsa", "",
       "Yeso patagónico (Río Negro es la principal provincia productora de yeso del país)",
       "General Roca, Río Negro",
       "General Roca", "Río Negro",
       [_e("Stefenelli, General Roca, Río Negro, Argentina"),
        _a("General Roca, Río Negro, Argentina")]),

    _r("IND-CEM-036", "Durlock S.A. (Grupo Etex, belga)",
       "Nueva planta Parque Industrial Roca II",
       "CEM", "Yeso", "Placas de yeso (nueva línea, abastece Patagonia y exportación a Chile)",
       "~70 empleos directos, ~200 indirectos",
       "Yeso patagónico (canteras cercanas a la planta)",
       "Parque Industrial Roca II, General Roca, Río Negro",
       "General Roca", "Río Negro",
       [_e("Parque Industrial Roca II, General Roca, Río Negro, Argentina"),
        _e("Parque Industrial, General Roca, Río Negro, Argentina"),
        _a("General Roca, Río Negro, Argentina")],
       notas="Anunciada en 2018, inversión $1.000M."),

    _r("IND-CEM-037", "Durlock S.A. / Grupo Etex", "Planta San Justo (fibrocemento)",
       "CEM", "Fibrocemento", "Placas de fibrocemento", "", "Cemento y fibras",
       "San Justo, La Matanza, Bs. As.",
       "San Justo", "Buenos Aires",
       [_ef("Durlock, San Justo, La Matanza, Buenos Aires, Argentina"),
        _a("San Justo, La Matanza, Buenos Aires, Argentina")]),

    # =====================================================================
    # 2. SIDERURGIA, METALURGIA Y PERFILERIA  (SID)
    # =====================================================================

    _r("IND-SID-001", "Ternium Argentina (ex Siderar/Somisa)", "Planta Savio / San Nicolás",
       "SID", "Acero plano",
       "Acero plano integrado (arrabio, planchones, laminados en caliente y frío)",
       "Capacidad histórica ampliada desde 2,5 Mt (1974); nueva colada continua +500.000 t/año planchones",
       "Mineral de hierro y carbón importados (puerto propio sobre el Paraná)",
       "Av. Savio s/n, San Nicolás de los Arroyos, Bs. As.",
       "San Nicolás de los Arroyos", "Buenos Aires",
       [_ef("Ternium, San Nicolás de los Arroyos, Buenos Aires, Argentina"),
        _e("Somisa, San Nicolás de los Arroyos, Buenos Aires, Argentina"),
        _e("Avenida Savio, San Nicolás de los Arroyos, Buenos Aires, Argentina"),
        _a("San Nicolás de los Arroyos, Buenos Aires, Argentina")],
       notas="Único complejo siderúrgico integrado del país (alto horno)."),

    _r("IND-SID-002", "Ternium Argentina (ex Siderar/Somisa)", "Planta Haedo",
       "SID", "Acero plano", "Laminados / productos terminados", "",
       "Semielaborados de San Nicolás",
       "Haedo, Bs. As.", "Haedo", "Buenos Aires",
       [_ef("Ternium, Haedo, Buenos Aires, Argentina"),
        _a("Haedo, Morón, Buenos Aires, Argentina")]),

    _r("IND-SID-003", "Ternium Argentina (ex Siderar/Somisa)", "Planta Canning",
       "SID", "Acero plano", "Productos de acero", "",
       "Semielaborados de San Nicolás",
       "Canning, Bs. As.", "Canning", "Buenos Aires",
       [_ef("Ternium, Canning, Buenos Aires, Argentina"),
        _a("Canning, Esteban Echeverría, Buenos Aires, Argentina")]),

    _r("IND-SID-004", "Ternium Argentina (ex Siderar/Somisa)", "Planta Ensenada",
       "SID", "Acero plano", "Laminación en frío", "",
       "Semielaborados de San Nicolás",
       "Ensenada, Bs. As. (ex Propulsora Siderúrgica, 1961)",
       "Ensenada", "Buenos Aires",
       [_ef("Ternium, Ensenada, Buenos Aires, Argentina"),
        _a("Ensenada, Buenos Aires, Argentina")]),

    _r("IND-SID-005", "Ternium Argentina (ex Siderar/Somisa)", "Planta Florencio Varela",
       "SID", "Acero plano", "Productos de acero", "",
       "Semielaborados de San Nicolás",
       "Florencio Varela, Bs. As.", "Florencio Varela", "Buenos Aires",
       [_ef("Ternium, Florencio Varela, Buenos Aires, Argentina"),
        _a("Florencio Varela, Buenos Aires, Argentina")]),

    _r("IND-SID-006", "Acindar (ArcelorMittal)", "Planta Villa Constitución",
       "SID", "Acero largo", "Acero no plano (barras, alambrón)",
       "~60% de la capacidad instalada nacional en laminados no planos",
       "Chatarra (horno eléctrico)",
       "Villa Constitución, Santa Fe", "Villa Constitución", "Santa Fe",
       [_ef("Acindar, Villa Constitución, Santa Fe, Argentina"),
        _a("Villa Constitución, Santa Fe, Argentina")]),

    _r("IND-SID-007", "Acindar (ArcelorMittal)", "Planta San Nicolás",
       "SID", "Acero largo", "Acero no plano", "", "Chatarra",
       "San Nicolás de los Arroyos, Bs. As.",
       "San Nicolás de los Arroyos", "Buenos Aires",
       [_ef("Acindar, San Nicolás de los Arroyos, Buenos Aires, Argentina"),
        _a("San Nicolás de los Arroyos, Buenos Aires, Argentina")]),

    _r("IND-SID-008", "Acindar (ArcelorMittal)", "Planta La Tablada",
       "SID", "Acero largo", "Productos de acero", "", "Semielaborados propios",
       "La Tablada, Bs. As.", "La Tablada", "Buenos Aires",
       [_ef("Acindar, La Tablada, Buenos Aires, Argentina"),
        _a("La Tablada, La Matanza, Buenos Aires, Argentina")]),

    _r("IND-SID-009", "Tenaris Siderca", "Planta Campana",
       "SID", "Tubos sin costura", "Tubos de acero sin costura",
       "900.000 t/año", "Chatarra / palanquilla",
       "Campana, Bs. As. (centro de producción desde 1954)",
       "Campana", "Buenos Aires",
       [_ef("Tenaris Siderca, Campana, Buenos Aires, Argentina"),
        _ef("Siderca, Campana, Buenos Aires, Argentina"),
        _a("Campana, Buenos Aires, Argentina")]),

    _r("IND-SID-010", "Tenaris (Siat)", "Planta Valentín Alsina",
       "SID", "Tubos con costura", "Tubos de acero con costura (soldado)",
       "", "Chapa laminada",
       "Valentín Alsina, Bs. As.", "Valentín Alsina", "Buenos Aires",
       [_ef("Siat, Valentín Alsina, Buenos Aires, Argentina"),
        _a("Valentín Alsina, Lanús, Buenos Aires, Argentina")]),

    _r("IND-SID-011", "Tenaris (Siat, ex línea de Acindar)", "Planta Villa Constitución",
       "SID", "Tubos con costura", "Tubos con costura",
       "80.000 t/año (capacidad de la línea adquirida a Acindar en 2006)",
       "Chapa laminada",
       "Villa Constitución, Santa Fe", "Villa Constitución", "Santa Fe",
       [_ef("Tenaris, Villa Constitución, Santa Fe, Argentina"),
        _a("Villa Constitución, Santa Fe, Argentina")]),

    _r("IND-SID-012", "Tenaris", "Planta Villa Mercedes",
       "SID", "Tubos de acero", "Tubos de acero", "", "Chapa/palanquilla",
       "Villa Mercedes, San Luis", "Villa Mercedes", "San Luis",
       [_ef("Tenaris, Villa Mercedes, San Luis, Argentina"),
        _a("Villa Mercedes, San Luis, Argentina")]),

    _r("IND-SID-013", "Acerbrag S.A.", "Planta Bragado",
       "SID", "Acero largo", "Acero no plano (construcción y agro)", "",
       "Chatarra (horno eléctrico)",
       "Bragado, Bs. As.", "Bragado", "Buenos Aires",
       [_ef("Acerbrag, Bragado, Buenos Aires, Argentina"),
        _a("Bragado, Buenos Aires, Argentina")]),

    _r("IND-SID-014", "Sipar Gerdau", "Planta Pérez",
       "SID", "Acero largo", "Barras de acero para hormigón",
       "Parte del total nacional de 7 Mt/año de acero crudo (capacidad instalada país)",
       "Chatarra",
       "Perez, Santa Fe (predio a confirmar)", "Pérez", "Santa Fe",
       [_ef("Gerdau, Pérez, Santa Fe, Argentina"),
        _ef("Sipar Gerdau, Pérez, Santa Fe, Argentina"),
        _a("Pérez, Santa Fe, Argentina")],
       notas="El documento marca el predio exacto como no confirmado."),

    _r("IND-SID-015", "Aceros Zapla", "Planta Palpalá",
       "SID", "Acero largo", "Acero para automotriz y petróleo/gas", "",
       "Chatarra / arrabio",
       "Palpalá, Jujuy", "Palpalá", "Jujuy",
       [_ef("Aceros Zapla, Palpalá, Jujuy, Argentina"),
        _a("Palpalá, Jujuy, Argentina")]),

    _r("IND-SID-016", "Aluar Aluminio Argentino S.A.I.C.", "Planta Puerto Madryn",
       "SID", "Aluminio", "Aluminio primario (placas, lingotes, barrotes, alambrón)",
       "460.000 t/año de aluminio primario (única planta de aluminio primario del país)",
       "Alúmina importada; energía de Central Hidroeléctrica Futaleufú (560 MW) + eólica (246 MW)",
       "Puerto Madryn, Chubut", "Puerto Madryn", "Chubut",
       [_ef("Aluar, Puerto Madryn, Chubut, Argentina"),
        _a("Puerto Madryn, Chubut, Argentina")]),

    _r("IND-SID-017", "Aluar Aluminio Argentino S.A.I.C.", "Planta Abasto",
       "SID", "Aluminio", "Aluminio elaborado (extrudidos y laminados, perfiles de aberturas)",
       "32.000 t/año de elaborados", "Aluminio primario de Puerto Madryn",
       "Abasto, La Plata, Bs. As.", "Abasto", "Buenos Aires",
       [_ef("Aluar, Abasto, La Plata, Buenos Aires, Argentina"),
        _a("Abasto, La Plata, Buenos Aires, Argentina")]),

    _r("IND-SID-018", "Barbieri", "Planta de perfiles de acero galvanizado liviano",
       "SID", "Perfilería galvanizada",
       "Perfiles galvanizados para steel frame y drywall", "",
       "Chapa galvanizada de Ternium",
       "Argentina (predio a confirmar; líder del segmento)", "", "",
       [], sin_ubicar=True,
       notas="El documento no consigna localidad. Requiere consulta a CASS."),

    # =====================================================================
    # 3. ARIDOS, CERAMICA ROJA Y PISOS  (ARI)
    # =====================================================================

    _r("IND-ARI-001", "Polo de canteras Tandilia/Ventania",
       "Canteras de granito y basalto",
       "ARI", "Áridos", "Áridos triturados (granito, basalto)",
       "s/d — mayor polo de trituración de rocas del país",
       "Yacimientos de rocas ígneas y metamórficas de Tandilia",
       "Olavarría y Azul (Tandilia); zona de Azul-Barker (Ventania), Bs. As.",
       "Olavarría", "Buenos Aires",
       [_a("Olavarría, Buenos Aires, Argentina")],
       tipo="POLO_REGIONAL",
       notas="Nodo regional agregado: representa el conjunto de canteras de Tandilia/Ventania, referenciado en Olavarría."),

    _r("IND-ARI-002", "Cerámica San Lorenzo (Grupo Lamosa)",
       "Planta Azul (porcelanato) — dos líneas",
       "ARI", "Porcelanato", "Porcelanato",
       "Producción anual del grupo: 15.000.000 m²/año (conjunto de plantas)",
       "Arcillas y feldespatos",
       "Azul, Bs. As.", "Azul", "Buenos Aires",
       [_ef("Cerámica San Lorenzo, Azul, Buenos Aires, Argentina"),
        _a("Azul, Buenos Aires, Argentina")]),

    _r("IND-ARI-003", "Cerámica San Lorenzo (Grupo Lamosa)", "Planta San Juan (cerámicos)",
       "ARI", "Cerámicos", "Cerámicos esmaltados",
       "Incluida en los 15.000.000 m²/año del grupo", "Arcillas locales",
       "San Juan (predio a confirmar)", "San Juan", "San Juan",
       [_a("San Juan, San Juan, Argentina")],
       notas="El documento sólo da la provincia; se referencia en la capital provincial."),

    _r("IND-ARI-004", "Cerro Negro (Sociedad Comercial del Plata)",
       "Planta industrial Buenos Aires",
       "ARI", "Cerámicos", "Cerámicos y porcelanatos", "",
       "Arcillas y feldespatos",
       "Buenos Aires y Córdoba (predios a confirmar)", "", "Buenos Aires",
       [], sin_ubicar=True,
       notas="El documento no da localidad; sólo provincia. No se georreferencia."),

    _r("IND-ARI-005", "Cerro Negro (Sociedad Comercial del Plata)",
       "Planta industrial Córdoba",
       "ARI", "Cerámicos", "Cerámicos y porcelanatos", "",
       "Arcillas y feldespatos",
       "Buenos Aires y Córdoba (predios a confirmar)", "", "Córdoba",
       [], sin_ubicar=True,
       notas="El documento no da localidad; sólo provincia. No se georreferencia."),

    _r("IND-ARI-006", "Ladrilleras y cavas de arcilla NEA",
       "Polo de extracción y cocción de ladrillo hueco",
       "ARI", "Cerámica roja", "Ladrillo cerámico hueco y macizo",
       "Sector altamente atomizado en pequeñas y medianas ladrilleras; sin dato agregado confiable de capacidad por planta",
       "Arcillas aluvionales del Litoral/NEA",
       "Chaco, Formosa y Corrientes (múltiples parajes y hornos de campaña, muy atomizado)",
       "Resistencia", "Chaco",
       [_a("Plaza 25 de Mayo, Resistencia, Chaco, Argentina"),
        _a("Resistencia, Chaco, Argentina")],
       tipo="POLO_REGIONAL",
       notas="Nodo regional agregado del NEA, referenciado en Resistencia."),

    _r("IND-ARI-007", "Quilmes, Fanelli, Palmar, Later-Cer y otras marcas de ladrillo hueco",
       "Plantas industriales de ladrillo hueco",
       "ARI", "Cerámica roja", "Ladrillo cerámico hueco", "", "Arcillas locales",
       "Buenos Aires y Litoral (predios individuales no confirmados en esta búsqueda)",
       "", "",
       [], sin_ubicar=True,
       notas="Segmento sin registro público centralizado de ubicación planta por planta."),

    # =====================================================================
    # 4. VIDRIO Y AISLACIONES  (VID)
    # =====================================================================

    _r("IND-VID-001", "VASA - Vidriería Argentina S.A. (NSG-Pilkington + Saint-Gobain)",
       "Planta Llavallol",
       "VID", "Vidrio plano",
       "Vidrio plano para arquitectura, automotriz, espejos, laminado",
       "s/d (en modernización, inversión de US$40M)",
       "Arena silícea, soda, caliza",
       "Llavallol, Lomas de Zamora, Bs. As. (73 años de operación)",
       "Llavallol", "Buenos Aires",
       [_ef("VASA Vidriería Argentina, Llavallol, Buenos Aires, Argentina"),
        _ef("Vidriería Argentina, Llavallol, Buenos Aires, Argentina"),
        _a("Llavallol, Lomas de Zamora, Buenos Aires, Argentina")]),

    _r("IND-VID-002", "VASA - Vidriería Argentina S.A. (NSG-Pilkington + Saint-Gobain)",
       "Planta Los Cardales / Exaltación de la Cruz",
       "VID", "Vidrio plano", "Vidrio plano flotado transparente",
       "800-1.000 t/día (según etapa del proyecto, inversión de US$215M)",
       "Arena silícea, soda, caliza",
       "Km 179, Ruta 6, Exaltación de la Cruz, Bs. As. (predio de 33 ha)",
       "Los Cardales", "Buenos Aires",
       [_ef("VASA, Los Cardales, Exaltación de la Cruz, Buenos Aires, Argentina"),
        _e("Los Cardales, Exaltación de la Cruz, Buenos Aires, Argentina"),
        _a("Exaltación de la Cruz, Buenos Aires, Argentina")],
       notas="Reemplaza a la ex planta de Campana."),

    _r("IND-VID-003", "Saint-Gobain Isover", "Planta de lana de vidrio Llavallol",
       "VID", "Aislaciones", "Lana de vidrio (aislación térmica/acústica)",
       "", "Vidrio reciclado, arena silícea",
       "Llavallol, Bs. As. (más de 60 años en el país)",
       "Llavallol", "Buenos Aires",
       [_ef("Saint-Gobain Isover, Llavallol, Buenos Aires, Argentina"),
        _a("Llavallol, Lomas de Zamora, Buenos Aires, Argentina")],
       notas="Único fabricante nacional de lana de vidrio; no existe producción local de lana de roca."),

    _r("IND-VID-004", "Grupo Estisol", "Planta EPS Isopor (Novapol) — Pilar",
       "VID", "Aislaciones",
       "Poliestireno expandido (EPS/Isopor) para construcción, embalaje y agro",
       "Parte de las 7 plantas del grupo (700+ empleados en total)",
       "Poliestireno expandible importado",
       "Pilar, Bs. As.", "Pilar", "Buenos Aires",
       [_ef("Isopor Novapol, Pilar, Buenos Aires, Argentina"),
        _a("Pilar, Buenos Aires, Argentina")]),

    _r("IND-VID-005", "Grupo Estisol", "Planta Edilteco Sudamericana — Pilar",
       "VID", "Aislaciones", "Mezclas aislantes cementicias para la construcción",
       "Incluida en el total del grupo", "Cemento y EPS",
       "Pilar, Bs. As.", "Pilar", "Buenos Aires",
       [_ef("Edilteco, Pilar, Buenos Aires, Argentina"),
        _a("Pilar, Buenos Aires, Argentina")]),

    _r("IND-VID-006", "Grupo Estisol", "Planta Concrehaus / Modus Building Panels — Pilar",
       "VID", "Aislaciones",
       "Paneles térmicos modulares para construcción (sistema Concrehaus/Modus)",
       "Ampliación de >5.000 m² en 2022 (US$10M, tecnología italiana)", "EPS + cemento",
       "Pilar (Villa Rosa), Bs. As.", "Villa Rosa", "Buenos Aires",
       [_ef("Concrehaus, Villa Rosa, Pilar, Buenos Aires, Argentina"),
        _a("Villa Rosa, Pilar, Buenos Aires, Argentina")]),

    _r("IND-VID-007", "Grupo Estisol", "Planta Paperfood — Pilar",
       "VID", "Envases", "Vasos y contenedores de papel (Polipapel)",
       "11.500.000 unidades/mes (línea Polipapel)", "Papel/cartón",
       "Pilar, Bs. As.", "Pilar", "Buenos Aires",
       [_ef("Paperfood, Pilar, Buenos Aires, Argentina"),
        _a("Pilar, Buenos Aires, Argentina")]),

    _r("IND-VID-008", "Grupo Estisol", "Planta Estisol Capital Federal",
       "VID", "Aislaciones", "EPS / productos derivados",
       "Incluida en el total del grupo", "Poliestireno expandible",
       "Parque Patricios, CABA", "Parque Patricios", "Ciudad Autónoma de Buenos Aires",
       [_a("Parque Patricios, Ciudad Autónoma de Buenos Aires, Argentina")]),

    _r("IND-VID-009", "Grupo Estisol", "Planta Estisol San Luis",
       "VID", "Aislaciones", "EPS para construcción y agro",
       "Incluida en el total del grupo", "Poliestireno expandible",
       "Parque Industrial, San Luis Capital, San Luis", "San Luis", "San Luis",
       [_e("Parque Industrial Norte, San Luis, San Luis, Argentina"),
        _a("San Luis, San Luis, Argentina")]),

    _r("IND-VID-010", "Grupo Estisol", "Planta Ecosol",
       "VID", "Aislaciones", "EPS", "Incluida en el total del grupo",
       "Poliestireno expandible",
       "Río Grande, Tierra del Fuego", "Río Grande", "Tierra del Fuego",
       [_a("Río Grande, Tierra del Fuego, Argentina")]),

    _r("IND-VID-011", "Grupo Estisol", "Planta Estisol Famaillá",
       "VID", "Aislaciones", "EPS", "Incluida en el total del grupo",
       "Poliestireno expandible",
       "Famaillá, Tucumán", "Famaillá", "Tucumán",
       [_a("Famaillá, Tucumán, Argentina")]),

    # =====================================================================
    # 5. INFRAESTRUCTURA HIDRICA Y POLIMEROS DE CONDUCCION  (HID)
    # =====================================================================

    _r("IND-HID-001", "Grupo DEMA", "Planta industrial San Justo",
       "HID", "Tubos poliméricos",
       "Tubos y accesorios en polímeros (agua, gas, cloaca — sistema Sigas Thermofusión), autopartes y accesorios de fundición",
       "", "Resinas PVC/PP/PE (nacionales e importadas)",
       "Av. Pres. Juan Domingo Perón 3750 (predio principal; oficinas también en Vicente López, Córdoba Capital y Mar del Plata)",
       "San Justo", "Buenos Aires",
       [_e("Avenida Presidente Juan Domingo Perón 3750, San Justo, La Matanza, Buenos Aires, Argentina"),
        _a("San Justo, La Matanza, Buenos Aires, Argentina")],
       notas="El documento da la calle y altura sin localidad; se resolvió como San Justo (La Matanza) según el domicilio corporativo publicado."),

    _r("IND-HID-002", "Industrias Saladillo S.A.", "Planta Parque Industrial Pilar",
       "HID", "Tubos poliméricos",
       "Sistemas de conducción de agua, desagüe, calefacción y gas (líneas Hidro 3, Awaduct, Hidroflex)",
       "s/d — empresa líder del segmento sanitario nacional", "Resinas PVC/PP-R",
       "Calle 9 N° 2639, Parque Industrial Pilar, Bs. As.", "Pilar", "Buenos Aires",
       [_ef("Industrias Saladillo, Parque Industrial Pilar, Buenos Aires, Argentina"),
        _e("Parque Industrial Pilar, Pilar, Buenos Aires, Argentina"),
        _a("Pilar, Buenos Aires, Argentina")]),

    _r("IND-HID-003", "Amanco Wavin Argentina (Orbia)", "Planta Pablo Podestá",
       "HID", "Tubos poliméricos",
       "Caños de PVC y PEAD para agua, cloaca, drenaje y gas (línea Novafort hasta 1 m de diámetro)",
       "", "Resinas PVC/PEAD",
       "Av. Pérez Galdós 8760, Pablo Podestá, Bs. As. (San Martín)",
       "Pablo Podestá", "Buenos Aires",
       [_ef("Amanco Wavin, Pablo Podestá, Buenos Aires, Argentina"),
        _e("Avenida Pérez Galdós 8760, Pablo Podestá, Buenos Aires, Argentina"),
        _a("Pablo Podestá, Tres de Febrero, Buenos Aires, Argentina")]),

    _r("IND-HID-004", "Grupo Rotoplas (mexicano)", "Planta Parque Industrial Pilar",
       "HID", "Tanques y termotanques",
       "Termotanques (línea Señorial); tanques, cisternas y plantas de tratamiento de agua",
       "1 termotanque cada 20 segundos; planta de 6.500 m² cubiertos sobre lote de 12.000 m²; 200 empleados",
       "Polietileno / chapa (termotanques)",
       "Parque Industrial Pilar, Bs. As.", "Pilar", "Buenos Aires",
       [_ef("Rotoplas, Parque Industrial Pilar, Buenos Aires, Argentina"),
        _e("Parque Industrial Pilar, Pilar, Buenos Aires, Argentina"),
        _a("Pilar, Buenos Aires, Argentina")],
       notas="Inaugurada en 2022; concebida como polo exportador regional del grupo."),

    _r("IND-HID-005", "Grupo Rotoplas (mexicano)", "Planta IPS",
       "HID", "Tubos poliméricos",
       "Tuberías y conexiones para agua y gas domiciliario",
       "Exporta a más de 35 países", "Resinas plásticas",
       "Argentina (predio a confirmar; empresa con +70 años en el país)", "", "",
       [], sin_ubicar=True,
       notas="El documento no consigna localidad."),

    _r("IND-HID-006", "Waterplast (Unike Group)", "Planta y sede Lanús Oeste",
       "HID", "Tanques", "Tanques, cisternas y biodigestores de agua", "",
       "Polietileno rotomoldeado",
       "Av. San Martín 2768, Lanús Oeste, Bs. As.", "Lanús Oeste", "Buenos Aires",
       [_e("Avenida San Martín 2768, Lanús Oeste, Buenos Aires, Argentina"),
        _a("Lanús Oeste, Lanús, Buenos Aires, Argentina")]),

    _r("IND-HID-007", "Tuboforte / Plásticos Tigre", "Planta industrial",
       "HID", "Tubos poliméricos", "Caños y conexiones plásticas", "",
       "Resinas plásticas",
       "Argentina (predio a confirmar)", "", "",
       [], sin_ubicar=True,
       notas="El documento declara explícitamente que no se pudo confirmar la localidad."),

    # =====================================================================
    # 6. MAQUINARIA PESADA, AGRICOLA, VIAL Y CARROCERIAS  (MAQ)
    # =====================================================================

    _r("IND-MAQ-001", "John Deere Argentina", "Planta Granadero Baigorria",
       "MAQ", "Tractores", "Tractores (series 5E, 6E, 6J, 7J) y motores",
       "~1.000 tractores/año (un turno, ampliable con doble turno); ~850-2.500 empleados según ciclo",
       "Componentes nacionales (fundiciones, cubiertas, baterías) + importados",
       "Juan Orsetti 481, Granadero Baigorria, Santa Fe (en el país desde 1958)",
       "Granadero Baigorria", "Santa Fe",
       [_ef("John Deere, Granadero Baigorria, Santa Fe, Argentina"),
        _e("Juan Orsetti 481, Granadero Baigorria, Santa Fe, Argentina"),
        _a("Granadero Baigorria, Santa Fe, Argentina")]),

    _r("IND-MAQ-002", "Pauny S.A. (ex Zanello)", "Planta Las Varillas",
       "MAQ", "Tractores", "Tractores",
       "~2.000 tractores/año (conjunto de sus dos plantas)",
       "Componentes nacionales e importados",
       "Las Varillas, Córdoba (adquirida en subasta 2003, ex activos de Zanello)",
       "Las Varillas", "Córdoba",
       [_ef("Pauny, Las Varillas, Córdoba, Argentina"),
        _a("Las Varillas, Córdoba, Argentina")]),

    _r("IND-MAQ-003", "Pauny S.A.", "Planta Santiago del Estero",
       "MAQ", "Tractores", "Tractores / componentes",
       "Incluida en los ~2.000 tractores/año del grupo", "",
       "Santiago del Estero (predio exacto a confirmar)",
       "Santiago del Estero", "Santiago del Estero",
       [_a("Santiago del Estero, Santiago del Estero, Argentina")],
       notas="El documento marca el predio exacto como no confirmado; se referencia en la capital provincial."),

    _r("IND-MAQ-004", "Agrinar (ex planta Massey Ferguson)", "Planta Granadero Baigorria",
       "MAQ", "Tractores", "Tractores y cosechadoras", "", "",
       "Granadero Baigorria, Santa Fe", "Granadero Baigorria", "Santa Fe",
       [_ef("Agrinar, Granadero Baigorria, Santa Fe, Argentina"),
        _a("Granadero Baigorria, Santa Fe, Argentina")]),

    _r("IND-MAQ-005", "CNH Industrial", "Planta Córdoba (Case IH / New Holland)",
       "MAQ", "Cosechadoras", "Cosechadoras y tractores", "", "",
       "Córdoba (predio a confirmar)", "Córdoba", "Córdoba",
       [_ef("CNH Industrial, Córdoba, Argentina"),
        _a("Córdoba, Córdoba, Argentina")],
       notas="El documento marca el predio exacto como no confirmado."),

    _r("IND-MAQ-006", "Agrale Argentina", "Planta de montaje Mercedes",
       "MAQ", "Tractores", "Tractores (montaje)", "",
       "Componentes importados de Brasil",
       "Mercedes, Bs. As.", "Mercedes", "Buenos Aires",
       [_ef("Agrale, Mercedes, Buenos Aires, Argentina"),
        _a("Mercedes, Buenos Aires, Argentina")]),

    _r("IND-MAQ-007", "Grupo Palmero (Michigan-Hanomag), Liugong, TBeH",
       "Plantas de palas y retroexcavadoras",
       "MAQ", "Maquinaria vial", "Máquinas viales y de movimiento de suelos",
       "", "Componentes propios e importados",
       "Argentina (predios individuales no confirmados)", "", "",
       [], sin_ubicar=True,
       notas="El documento recomienda consulta directa a CIPIBIC."),

    # --- 6.bis Remolques, semirremolques y acoplados ---------------------
    _r("IND-MAQ-008", "Metalúrgica Hermann S.R.L.", "Planta Parque Industrial Gualeguaychú",
       "MAQ", "Remolques", "Acoplados, carrocerías, semirremolques y bitrenes",
       "Líder nacional desde 2006, ~15% del mercado; planta de 26.500 m² cubiertos en predio de 8 ha; ~130 unidades/mes, ~300 empleados",
       "Chapa y perfiles de acero",
       "Parque Industrial Gualeguaychú (Ruta Nacional 14), Gualeguaychú, Entre Ríos",
       "Gualeguaychú", "Entre Ríos",
       [_ef("Metalúrgica Hermann, Gualeguaychú, Entre Ríos, Argentina"),
        _e("Parque Industrial Gualeguaychú, Gualeguaychú, Entre Ríos, Argentina"),
        _a("Gualeguaychú, Entre Ríos, Argentina")]),

    _r("IND-MAQ-009", "Sola y Brusa S.A.", "Planta Franck",
       "MAQ", "Remolques",
       "Semirremolques (bateas, portacontenedores, ganaderos doble piso)",
       "2° lugar en patentamientos (77 u./mes en pico reciente); fundada en 1961",
       "Chapa y perfiles de acero",
       "Ruta Provincial N°6 km 7, Franck, Santa Fe", "Franck", "Santa Fe",
       [_ef("Sola y Brusa, Franck, Santa Fe, Argentina"),
        _a("Franck, Santa Fe, Argentina")]),

    _r("IND-MAQ-010", "Semirremolques Vulcano S.A.", "Planta Las Rosas",
       "MAQ", "Remolques", "Semirremolques",
       "Su titular (Carlos Moriconi) presidió la CAFAS", "Chapa y perfiles de acero",
       "Ruta 178, Av. Dickinson 1151, Las Rosas, Santa Fe", "Las Rosas", "Santa Fe",
       [_ef("Semirremolques Vulcano, Las Rosas, Santa Fe, Argentina"),
        _e("Avenida Dickinson 1151, Las Rosas, Santa Fe, Argentina"),
        _a("Las Rosas, Santa Fe, Argentina")]),

    _r("IND-MAQ-011", "Helvética S.A.", "Planta Cañada de Gómez",
       "MAQ", "Remolques", "Acoplados y semirremolques",
       "Líder histórico (fundada en 1904); nave de 15.000 m² cubiertos en predio de 9 ha",
       "Chapa y perfiles de acero",
       "Parque Industrial de Cañada de Gómez (Ruta Nac. 9 y Ruta Prov. 91), Santa Fe",
       "Cañada de Gómez", "Santa Fe",
       [_ef("Helvética, Cañada de Gómez, Santa Fe, Argentina"),
        _e("Parque Industrial Cañada de Gómez, Santa Fe, Argentina"),
        _a("Cañada de Gómez, Santa Fe, Argentina")]),

    _r("IND-MAQ-012", "Randon Argentina S.A. (brasileña)", "Planta en Argentina",
       "MAQ", "Remolques", "Semirremolques",
       "~7% del mercado; única de las 12 principales que no es de capital nacional",
       "Chapa y perfiles de acero",
       "Argentina (inscripta en DNRPA; predio exacto no confirmado en esta ronda)",
       "", "",
       [], sin_ubicar=True,
       notas="El documento declara el predio como no confirmado."),

    _r("IND-MAQ-013", "Lambert Hermanos", "Planta Concepción del Uruguay",
       "MAQ", "Remolques", "Acoplados y semirremolques",
       "9° en patentamientos nacionales (2020)", "Chapa y perfiles de acero",
       "Concepción del Uruguay, Entre Ríos", "Concepción del Uruguay", "Entre Ríos",
       [_ef("Lambert Hermanos, Concepción del Uruguay, Entre Ríos, Argentina"),
        _a("Concepción del Uruguay, Entre Ríos, Argentina")]),

    _r("IND-MAQ-014", "Acoplados Gross (Sucesores de Emilio Gross S.R.L.)",
       "Planta General Ramírez",
       "MAQ", "Remolques", "Acoplados y semirremolques",
       "11° en patentamientos nacionales (2020)", "Chapa y perfiles de acero",
       "República de Entre Ríos 1880, General Ramírez, Entre Ríos",
       "General Ramírez", "Entre Ríos",
       [_e("República de Entre Ríos 1880, General Ramírez, Entre Ríos, Argentina"),
        _a("General Ramírez, Entre Ríos, Argentina")]),

    _r("IND-MAQ-015", "Cometto S.A.", "Planta Tortuguitas",
       "MAQ", "Remolques",
       "Semirremolques especiales y equipos de transporte pesado",
       "Miembro fundador de CAFAS", "Chapa y perfiles de acero",
       "Ruta Panamericana km 35,700 y Henry Ford, Tortuguitas, Buenos Aires",
       "Tortuguitas", "Buenos Aires",
       [_ef("Cometto, Tortuguitas, Buenos Aires, Argentina"),
        _a("Tortuguitas, Malvinas Argentinas, Buenos Aires, Argentina")]),

    _r("IND-MAQ-016", "Danés S.R.L.", "Planta Roldán",
       "MAQ", "Remolques", "Acoplados y semirremolques", "",
       "Chapa y perfiles de acero",
       "Ruta A-012 km 52, Roldán, Santa Fe", "Roldán", "Santa Fe",
       [_ef("Danés, Roldán, Santa Fe, Argentina"),
        _a("Roldán, Santa Fe, Argentina")]),

    _r("IND-MAQ-017", "SICA Metalúrgica Argentina S.A.", "Planta Esperanza",
       "MAQ", "Remolques", "Acoplados y semirremolques", "",
       "Chapa y perfiles de acero",
       "Rvdo. Padre Kreder 3746, Esperanza, Santa Fe", "Esperanza", "Santa Fe",
       [_ef("SICA Metalúrgica, Esperanza, Santa Fe, Argentina"),
        _e("Reverendo Padre Kreder 3746, Esperanza, Santa Fe, Argentina"),
        _a("Esperanza, Santa Fe, Argentina")]),

    _r("IND-MAQ-018", "Taboga Hnos. S.A.C.I.", "Planta Marcos Juárez",
       "MAQ", "Remolques", "Acoplados (marca \"El Fierro\")", "",
       "Chapa y perfiles de acero",
       "Av. Intendente Loinás 60, Marcos Juárez, Córdoba", "Marcos Juárez", "Córdoba",
       [_ef("Taboga Hnos, Marcos Juárez, Córdoba, Argentina"),
        _a("Marcos Juárez, Córdoba, Argentina")]),

    _r("IND-MAQ-019", "INDASYC S.A.", "Planta Trelew",
       "MAQ", "Remolques", "Acoplados y semirremolques (marca Sayi)",
       "Única fábrica del rubro identificada en la Patagonia",
       "Chapa y perfiles de acero",
       "Ruta Nacional N°3 km 1.460, Trelew, Chubut", "Trelew", "Chubut",
       [_ef("Indasyc, Trelew, Chubut, Argentina"),
        _a("Trelew, Chubut, Argentina")]),

    # =====================================================================
    # 7. MOLINERIA Y ALIMENTOS BASICOS A GRANEL  (MOL)
    # =====================================================================

    _r("IND-MOL-001", "Molino Cañuelas (Grupo Navilli)", "Planta Cañuelas",
       "MOL", "Molinería", "Harina de trigo, premezclas",
       "Molino Cañuelas procesa ~28,5% de la molienda total de trigo del país (grupo, 11 plantas + 2 de Molinos Florencia)",
       "Trigo nacional",
       "Cañuelas, Bs. As. (sede fundacional, 1976)", "Cañuelas", "Buenos Aires",
       [_ef("Molino Cañuelas, Cañuelas, Buenos Aires, Argentina"),
        _a("Cañuelas, Buenos Aires, Argentina")]),

    _r("IND-MOL-002", "Molino Cañuelas (Grupo Navilli)", "Planta Carlos Spegazzini (Ezeiza)",
       "MOL", "Molinería", "Harinas, aceites, congelados, galletitas",
       "Parte de la expansión financiada con crédito IFC/Banco Mundial de US$80M",
       "Trigo/oleaginosas nacionales",
       "Carlos Spegazzini, Ezeiza, Bs. As.", "Carlos Spegazzini", "Buenos Aires",
       [_ef("Molino Cañuelas, Carlos Spegazzini, Buenos Aires, Argentina"),
        _a("Carlos Spegazzini, Ezeiza, Buenos Aires, Argentina")]),

    _r("IND-MOL-003", "Molino Cañuelas (Grupo Navilli)", "Planta Pilar",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de 11 plantas bonaerenses del grupo", "Trigo nacional",
       "Bs. As. (varias localidades)", "Pilar", "Buenos Aires",
       [_ef("Molino Cañuelas, Pilar, Buenos Aires, Argentina"),
        _a("Pilar, Buenos Aires, Argentina")]),

    _r("IND-MOL-004", "Molino Cañuelas (Grupo Navilli)", "Planta Chacabuco",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de 11 plantas bonaerenses del grupo", "Trigo nacional",
       "Bs. As. (varias localidades)", "Chacabuco", "Buenos Aires",
       [_ef("Molino Cañuelas, Chacabuco, Buenos Aires, Argentina"),
        _a("Chacabuco, Buenos Aires, Argentina")]),

    _r("IND-MOL-005", "Molino Cañuelas (Grupo Navilli)", "Planta San Justo",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de 11 plantas bonaerenses del grupo", "Trigo nacional",
       "Bs. As. (varias localidades)", "San Justo", "Buenos Aires",
       [_ef("Molino Cañuelas, San Justo, La Matanza, Buenos Aires, Argentina"),
        _a("San Justo, La Matanza, Buenos Aires, Argentina")]),

    _r("IND-MOL-006", "Molino Cañuelas (Grupo Navilli)", "Planta Tres Arroyos",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de 11 plantas bonaerenses del grupo", "Trigo nacional",
       "Bs. As. (varias localidades)", "Tres Arroyos", "Buenos Aires",
       [_ef("Molino Cañuelas, Tres Arroyos, Buenos Aires, Argentina"),
        _a("Tres Arroyos, Buenos Aires, Argentina")]),

    _r("IND-MOL-007", "Molino Cañuelas (Grupo Navilli)", "Planta Pigüé",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de 11 plantas bonaerenses del grupo", "Trigo nacional",
       "Bs. As. (varias localidades)", "Pigüé", "Buenos Aires",
       [_ef("Molino Cañuelas, Pigüé, Buenos Aires, Argentina"),
        _a("Pigüé, Saavedra, Buenos Aires, Argentina")]),

    _r("IND-MOL-008", "Molino Cañuelas (Grupo Navilli)", "Planta Rosario",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de plantas del grupo", "Trigo nacional",
       "Rosario y Santa Fe Capital", "Rosario", "Santa Fe",
       [_ef("Molino Cañuelas, Rosario, Santa Fe, Argentina"),
        _a("Rosario, Santa Fe, Argentina")]),

    _r("IND-MOL-009", "Molino Cañuelas (Grupo Navilli)", "Planta Santa Fe Capital",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de plantas del grupo", "Trigo nacional",
       "Rosario y Santa Fe Capital", "Santa Fe", "Santa Fe",
       [_a("Santa Fe, Santa Fe, Argentina")]),

    _r("IND-MOL-010", "Molino Cañuelas (Grupo Navilli)", "Planta Resistencia",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de plantas del grupo", "Trigo nacional",
       "Resistencia, Chaco", "Resistencia", "Chaco",
       [_ef("Molino Cañuelas, Resistencia, Chaco, Argentina"),
        _a("Plaza 25 de Mayo, Resistencia, Chaco, Argentina"),
        _a("Resistencia, Chaco, Argentina")]),

    _r("IND-MOL-011", "Molino Cañuelas (Grupo Navilli)", "Planta Realicó",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de plantas del grupo", "Trigo nacional",
       "Realicó, La Pampa", "Realicó", "La Pampa",
       [_ef("Molino Cañuelas, Realicó, La Pampa, Argentina"),
        _a("Realicó, La Pampa, Argentina")]),

    _r("IND-MOL-012", "Molino Cañuelas (Grupo Navilli)", "Planta Salta Capital",
       "MOL", "Molinería", "Molienda de trigo",
       "Incluida en el total de plantas del grupo", "Trigo nacional",
       "Salta Capital", "Salta", "Salta",
       [_a("Salta, Salta, Argentina")]),

    _r("IND-MOL-013", "Molino Cañuelas (Grupo Navilli)", "Planta Adelia María",
       "MOL", "Molinería", "Molienda de trigo (una de las mayores del país por t/día)",
       "Entre las 4 mayores plantas harineras del país", "Trigo nacional",
       "Adelia María, Córdoba", "Adelia María", "Córdoba",
       [_ef("Molino Cañuelas, Adelia María, Córdoba, Argentina"),
        _a("Adelia María, Córdoba, Argentina")]),

    _r("IND-MOL-014", "Molino Florencia (Grupo Cañuelas)", "Planta Laboulaye",
       "MOL", "Molinería", "Harina de trigo", "~720 t/día de molienda", "Trigo nacional",
       "Laboulaye, Córdoba", "Laboulaye", "Córdoba",
       [_ef("Molino Florencia, Laboulaye, Córdoba, Argentina"),
        _a("Laboulaye, Córdoba, Argentina")]),

    _r("IND-MOL-015", "Molino Florencia (Grupo Cañuelas)", "Planta Córdoba Capital",
       "MOL", "Molinería", "Harina de trigo", "", "Trigo nacional",
       "Córdoba Capital", "Córdoba", "Córdoba",
       [_a("Córdoba, Córdoba, Argentina")]),

    _r("IND-MOL-016", "Molino Cañuelas (Grupo Navilli)", "Terminal Las Palmas (puerto propio)",
       "MOL", "Puerto cerealero",
       "Puerto cerealero y de carga general (exportación)", "", "",
       "Zárate, Bs. As. (predio de 85 ha sobre el Paraná de las Palmas)",
       "Zárate", "Buenos Aires",
       [_ef("Terminal Las Palmas, Zárate, Buenos Aires, Argentina"),
        _a("Zárate, Buenos Aires, Argentina")],
       tipo="PUERTO"),

    _r("IND-MOL-017", "Cargill SACI", "Planta Pilar",
       "MOL", "Molinería", "Molienda de trigo",
       "1.400 t/día — el molino más grande del país", "Trigo nacional",
       "Pilar, Bs. As.", "Pilar", "Buenos Aires",
       [_ef("Cargill, Pilar, Buenos Aires, Argentina"),
        _a("Pilar, Buenos Aires, Argentina")]),

    _r("IND-MOL-018", "José Minetti y Cía. Ltda.", "Planta Córdoba",
       "MOL", "Molinería", "Molienda de trigo", "820 t/día", "Trigo nacional",
       "Córdoba Capital", "Córdoba", "Córdoba",
       [_ef("Molino Minetti, Córdoba, Argentina"),
        _a("Córdoba, Córdoba, Argentina")]),

    _r("IND-MOL-019", "Molinos Río de la Plata", "Planta histórica Puerto Madero",
       "MOL", "Molinería",
       "Molienda de trigo (origen histórico; verificar operación actual)",
       "Molinos participa con ~35-38% de la molienda de trigo candeal", "Trigo nacional",
       "Dique III, Puerto Madero, CABA", "Puerto Madero", "Ciudad Autónoma de Buenos Aires",
       [_e("Dique 3, Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina"),
        _a("Puerto Madero, Ciudad Autónoma de Buenos Aires, Argentina")],
       notas="Origen 1902. El propio documento sugiere verificar si la molienda sigue operativa en el sitio."),

    _r("IND-MOL-020", "Compañía Molinera del Sur SACEI", "Planta Bahía Blanca",
       "MOL", "Molinería", "Molienda de trigo candeal",
       "~26-27% de participación en trigo candeal (6.500-7.000 t/mes)",
       "Trigo candeal del sur bonaerense",
       "Bahía Blanca, Bs. As.", "Bahía Blanca", "Buenos Aires",
       [_a("Bahía Blanca, Buenos Aires, Argentina")]),

    _r("IND-MOL-021", "Molino Tres Arroyos", "Planta Tres Arroyos",
       "MOL", "Molinería", "Molienda de trigo candeal",
       "~12-13% de participación en trigo candeal (3.500-3.800 t/mes)", "Trigo candeal",
       "Tres Arroyos, Bs. As.", "Tres Arroyos", "Buenos Aires",
       [_a("Tres Arroyos, Buenos Aires, Argentina")],
       notas="La consulta por nombre de planta resolvía a otro molino del partido (Micaela Cascallares); se usa el centroide de la ciudad."),

    _r("IND-MOL-022", "Nodos Up-River (acopio y molienda de granos)", "Terminales portuarias Up-River",
       "MOL", "Agroexportación",
       "Acopio, molienda y exportación de granos y subproductos",
       "Mayor polo agroexportador de granos y oleaginosas del país",
       "Soja, maíz, trigo del área núcleo pampeana",
       "San Lorenzo, Puerto General San Martín y Timbúes, Santa Fe",
       "San Lorenzo", "Santa Fe",
       [_a("San Lorenzo, Santa Fe, Argentina")],
       tipo="POLO_REGIONAL",
       notas="Nodo regional agregado (San Lorenzo - Puerto General San Martín - Timbúes), referenciado en San Lorenzo."),

    _r("IND-MOL-023", "Cuenca lechera Santa Fe centro", "Polo de usinas lácteas",
       "MOL", "Lácteos", "Leche fluida y productos lácteos",
       "Una de las tres principales cuencas lecheras del país",
       "Leche de tambos de la región",
       "Zona centro de Santa Fe (Rafaela y alrededores)", "Rafaela", "Santa Fe",
       [_a("Rafaela, Santa Fe, Argentina")],
       tipo="POLO_REGIONAL",
       notas="Nodo regional agregado, referenciado en Rafaela."),

    _r("IND-MOL-024", "Cuenca lechera Córdoba este", "Polo de usinas lácteas",
       "MOL", "Lácteos", "Leche fluida y productos lácteos", "",
       "Leche de tambos de la región",
       "Este de Córdoba (Villa María, San Francisco y alrededores)",
       "Villa María", "Córdoba",
       [_a("Villa María, Córdoba, Argentina")],
       tipo="POLO_REGIONAL",
       notas="Nodo regional agregado, referenciado en Villa María."),

    _r("IND-MOL-025", "Cuenca lechera Buenos Aires (abasto y oeste)", "Polo de usinas lácteas",
       "MOL", "Lácteos", "Leche fluida y productos lácteos", "",
       "Leche de tambos de la región",
       "Oeste bonaerense y cuenca de abasto (Cañuelas, Chascomús, Lincoln, etc.)",
       "Cañuelas", "Buenos Aires",
       [_a("Cañuelas, Buenos Aires, Argentina")],
       tipo="POLO_REGIONAL",
       notas="Nodo regional agregado, referenciado en Cañuelas."),

    # --- 7.bis Lacteos ---------------------------------------------------
    _r("IND-MOL-026", "Mastellone Hnos. S.A. (La Serenísima)",
       "Complejo Industrial Pascual Mastellone",
       "MOL", "Lácteos", "Leche fluida, yogures, postres (planta insignia del grupo)",
       "Grupo recibe 3.500.000 litros/día a nivel nacional",
       "Leche de tambos del corredor bonaerense",
       "Almirante Brown 957, General Rodríguez, Bs. As. (52 km de CABA)",
       "General Rodríguez", "Buenos Aires",
       [_ef("Mastellone Hnos, General Rodríguez, Buenos Aires, Argentina"),
        _ef("La Serenísima, General Rodríguez, Buenos Aires, Argentina"),
        _a("General Rodríguez, Buenos Aires, Argentina")],
       notas="Bajo control conjunto Arcor/Danone."),

    _r("IND-MOL-027", "Mastellone Hnos. S.A. (La Serenísima)", "Planta Longchamps",
       "MOL", "Lácteos", "Productos lácteos", "Incluida en el total del grupo",
       "Leche de tambos bonaerenses",
       "Longchamps, Bs. As.", "Longchamps", "Buenos Aires",
       [_ef("Mastellone, Longchamps, Buenos Aires, Argentina"),
        _a("Longchamps, Almirante Brown, Buenos Aires, Argentina")]),

    _r("IND-MOL-028", "Mastellone Hnos. S.A. (La Serenísima)", "Planta Trenque Lauquen",
       "MOL", "Lácteos", "Productos lácteos", "Incluida en el total del grupo",
       "Leche de tambos del oeste bonaerense",
       "Trenque Lauquen, Bs. As.", "Trenque Lauquen", "Buenos Aires",
       [_ef("Mastellone, Trenque Lauquen, Buenos Aires, Argentina"),
        _a("Trenque Lauquen, Buenos Aires, Argentina")]),

    _r("IND-MOL-029", "Mastellone Hnos. S.A. (La Serenísima)", "Planta Leubucó",
       "MOL", "Lácteos", "Productos lácteos", "Incluida en el total del grupo",
       "Leche de tambos bonaerenses",
       "Leubucó, Bs. As.", "Leubucó", "Buenos Aires",
       [_e("Leubucó, Buenos Aires, Argentina"),
        _a("Trenque Lauquen, Buenos Aires, Argentina")],
       notas="El documento no consigna el partido; OSM resuelve el paraje Leubucó en el partido de Adolfo Alsina."),

    _r("IND-MOL-030", "Mastellone Hnos. S.A. (La Serenísima)", "Planta Tandil",
       "MOL", "Lácteos", "Productos lácteos", "Incluida en el total del grupo",
       "Leche de tambos bonaerenses",
       "Tandil, Bs. As.", "Tandil", "Buenos Aires",
       [_ef("Mastellone, Tandil, Buenos Aires, Argentina"),
        _a("Tandil, Buenos Aires, Argentina")]),

    _r("IND-MOL-031", "Mastellone Hnos. S.A. (La Serenísima)", "Planta Canals",
       "MOL", "Lácteos", "Productos lácteos", "Incluida en el total del grupo",
       "Leche de tambos cordobeses",
       "Canals, Córdoba", "Canals", "Córdoba",
       [_ef("Mastellone, Canals, Córdoba, Argentina"),
        _a("Canals, Córdoba, Argentina")]),

    _r("IND-MOL-032", "Mastellone Hnos. S.A. (La Serenísima)", "Planta Villa Mercedes",
       "MOL", "Lácteos", "Productos lácteos", "Incluida en el total del grupo",
       "Leche de tambos regionales",
       "Villa Mercedes, San Luis", "Villa Mercedes", "San Luis",
       [_ef("Mastellone, Villa Mercedes, San Luis, Argentina"),
        _a("Villa Mercedes, San Luis, Argentina")]),

    _r("IND-MOL-033", "Mastellone Hnos. S.A. (La Serenísima)",
       "Planta histórica La Martona (ex Vicente Casares)",
       "MOL", "Lácteos",
       "Marca histórica (primera láctea argentina, 1889; adquirida en 1978)",
       "", "",
       "Vicente Casares, Cañuelas, Bs. As.", "Vicente Casares", "Buenos Aires",
       [_e("Vicente Casares, Cañuelas, Buenos Aires, Argentina"),
        _a("Cañuelas, Buenos Aires, Argentina")],
       notas="Valor patrimonial de marca; el pueblo de Vicente Casares nació alrededor de la usina."),

    _r("IND-MOL-034", "SanCor Cooperativas Unidas Ltda.", "Planta Sunchales (sede central)",
       "MOL", "Lácteos",
       "Leche UAT, leche en polvo, dulce de leche (llegó a procesar 2.000.000 l/día; hoy <10% de utilización)",
       "Valuada en US$2,4M (subasta 2026)", "Leche de tambos de Santa Fe/Córdoba",
       "Sunchales, Santa Fe", "Sunchales", "Santa Fe",
       [_ef("SanCor, Sunchales, Santa Fe, Argentina"),
        _a("Sunchales, Santa Fe, Argentina")],
       estado_operativo="EN_QUIEBRA/SUBASTA",
       notas="En quiebra desde 2026; subasta judicial en curso (base US$52,1M por 6 plantas + marcas)."),

    _r("IND-MOL-035", "SanCor Cooperativas Unidas Ltda.", "Planta Gálvez",
       "MOL", "Lácteos", "Maduración y fraccionamiento/empaque de quesos",
       "Valuada en US$5,5M (subasta 2026)", "Leche de tambos regionales",
       "Gálvez, Santa Fe", "Gálvez", "Santa Fe",
       [_ef("SanCor, Gálvez, Santa Fe, Argentina"),
        _a("Gálvez, Santa Fe, Argentina")],
       estado_operativo="EN_QUIEBRA/SUBASTA"),

    _r("IND-MOL-036", "SanCor Cooperativas Unidas Ltda.", "Planta San Guillermo",
       "MOL", "Lácteos", "Queso en barra y mozzarella",
       "Valuada en US$2,5M (subasta 2026); paralizada desde dic. 2025",
       "Leche de tambos regionales",
       "San Guillermo, Depto. San Cristóbal, Santa Fe", "San Guillermo", "Santa Fe",
       [_ef("SanCor, San Guillermo, Santa Fe, Argentina"),
        _a("San Guillermo, Santa Fe, Argentina")],
       estado_operativo="EN_QUIEBRA/SUBASTA"),

    _r("IND-MOL-037", "SanCor Cooperativas Unidas Ltda.", "Planta Devoto",
       "MOL", "Lácteos", "Crema, manteca y queso untable (Mendicrim)",
       "Valuada en US$7M (subasta 2026)", "Leche de tambos cordobeses",
       "Devoto, Córdoba", "Devoto", "Córdoba",
       [_ef("SanCor, Devoto, Córdoba, Argentina"),
        _a("Devoto, Córdoba, Argentina")],
       estado_operativo="EN_QUIEBRA/SUBASTA"),

    _r("IND-MOL-038", "SanCor Cooperativas Unidas Ltda.", "Planta Balnearia",
       "MOL", "Lácteos", "Quesos semiduros (pategrás, danbo, fontina, sardo)",
       "Valuada en US$5M (subasta 2026)", "Leche de tambos cordobeses",
       "Balnearia, Córdoba", "Balnearia", "Córdoba",
       [_ef("SanCor, Balnearia, Córdoba, Argentina"),
        _a("Balnearia, Córdoba, Argentina")],
       estado_operativo="EN_QUIEBRA/SUBASTA"),

    _r("IND-MOL-039", "SanCor Cooperativas Unidas Ltda.", "Planta La Carlota",
       "MOL", "Lácteos", "Quesos duros y de rallar",
       "Valuada en US$5M (subasta 2026)", "Leche de tambos cordobeses",
       "La Carlota, Córdoba", "La Carlota", "Córdoba",
       [_ef("SanCor, La Carlota, Córdoba, Argentina"),
        _a("La Carlota, Córdoba, Argentina")],
       estado_operativo="EN_QUIEBRA/SUBASTA"),

    _r("IND-MOL-040", "Adecoagro (Grupo Lácteo)", "Planta Chivilcoy (ex SanCor)",
       "MOL", "Lácteos",
       "Productos lácteos (marcas Las Tres Niñas, Angelita, Apóstoles)",
       "1.100.000 litros/día de recepción a nivel grupo",
       "Leche de tambos propios y de terceros",
       "Chivilcoy, Bs. As.", "Chivilcoy", "Buenos Aires",
       [_ef("Adecoagro, Chivilcoy, Buenos Aires, Argentina"),
        _a("Chivilcoy, Buenos Aires, Argentina")],
       notas="Comprada a SanCor en 2018 (operación conjunta con Morteros, US$45M)."),

    _r("IND-MOL-041", "Adecoagro (Grupo Lácteo)", "Planta Morteros (ex SanCor)",
       "MOL", "Lácteos", "Productos lácteos", "Incluida en el total del grupo",
       "Leche de tambos regionales",
       "Morteros, Córdoba", "Morteros", "Córdoba",
       [_ef("Adecoagro, Morteros, Córdoba, Argentina"),
        _a("Morteros, Córdoba, Argentina")],
       notas="Comprada a SanCor en 2018 (operación conjunta con Chivilcoy, US$45M)."),

    _r("IND-MOL-042", "Savencia Fromage & Dairy (ex Bongrain) — Milkaut", "Planta Milkaut — Franck",
       "MOL", "Lácteos", "Quesos, leche en polvo y derivados",
       "Grupo recibe 1.700.000 litros/día a nivel nacional",
       "Leche de tambos santafesinos",
       "Franck, Santa Fe", "Franck", "Santa Fe",
       [_ef("Milkaut, Franck, Santa Fe, Argentina"),
        _a("Franck, Santa Fe, Argentina")]),

    _r("IND-MOL-043", "Savencia Fromage & Dairy — Ilolay (ex Suc. de Alfredo Williner)",
       "Planta Ilolay — Rafaela",
       "MOL", "Lácteos",
       "Quesos, yogures, leche larga vida y en polvo (25% de ventas al exterior)",
       "Incluida en el total del grupo Savencia", "Leche de tambos santafesinos",
       "Rafaela, Santa Fe", "Rafaela", "Santa Fe",
       [_ef("Ilolay, Rafaela, Santa Fe, Argentina"),
        _a("Rafaela, Santa Fe, Argentina")]),

    _r("IND-MOL-044", "Saputo Argentina (canadiense, ex Vicentín/CityLab)", "Planta Rafaela",
       "MOL", "Lácteos", "Productos lácteos",
       "Líder del ranking 2025-2026: 3.800.000 litros/día de recepción",
       "Leche de tambos santafesinos",
       "Rafaela, Santa Fe", "Rafaela", "Santa Fe",
       [_ef("Saputo, Rafaela, Santa Fe, Argentina"),
        _a("Rafaela, Santa Fe, Argentina")]),

    _r("IND-MOL-045", "Punta del Agua S.A.", "Planta Punta del Agua",
       "MOL", "Lácteos", "Productos lácteos",
       "1.300.000 litros/día de recepción", "Leche de tambos cordobeses",
       "Córdoba (zona a confirmar)", "Punta del Agua", "Córdoba",
       [_a("Punta del Agua, Córdoba, Argentina"),
        _a("Córdoba, Córdoba, Argentina")],
       notas="Grupo cordobés; el documento marca la zona como no confirmada. La coordenada corresponde al paraje Punta del Agua (Depto. Río Cuarto) y debe verificarse contra la empresa."),

    # =====================================================================
    # 8. NODOS ENERGETICOS Y MATERIAL ELECTRICO PESADO  (ENE)
    # =====================================================================

    _r("IND-ENE-001", "Tadeo Czerweny S.A.", "Planta industrial Gálvez",
       "ENE", "Transformadores",
       "Transformadores de distribución y potencia, subestaciones móviles",
       "Transformadores de potencia hasta 100-300 MVA y hasta 500 kV",
       "Chapa magnética, cobre, aislantes (mayormente importados)",
       "Bv. Argentino 374, Gálvez, Santa Fe", "Gálvez", "Santa Fe",
       [_ef("Tadeo Czerweny, Gálvez, Santa Fe, Argentina"),
        _e("Bulevar Argentino 374, Gálvez, Santa Fe, Argentina"),
        _a("Gálvez, Santa Fe, Argentina")]),

    _r("IND-ENE-002", "Prysmian Energía Cables y Sistemas de Argentina", "Planta \"La Rosa\"",
       "ENE", "Cables de potencia",
       "Cables de energía de media y alta tensión (hasta 245 kV) y cables ópticos",
       "Centro de excelencia sudamericano para cables subterráneos de alta tensión (132-220 kV); inversión de US$15M en nueva línea (2018)",
       "Cobre, aluminio, XLPE",
       "Barrio de Mataderos, CABA", "Mataderos", "Ciudad Autónoma de Buenos Aires",
       [_ef("Prysmian, Mataderos, Ciudad Autónoma de Buenos Aires, Argentina"),
        _a("Mataderos, Ciudad Autónoma de Buenos Aires, Argentina")]),

    _r("IND-ENE-003", "IMSA (Industria Metalúrgica Sud Americana)", "Planta industrial Merlo",
       "ENE", "Cables de potencia",
       "Cables eléctricos de baja/media/alta tensión, alambres esmaltados de cobre y aluminio, metales semielaborados",
       "s/d (planta integrada: laminación en caliente y frío de cobre, colada continua de alambrón, líneas de vulcanización y catenaria para MT/AT)",
       "Cobre y aluminio (colada continua propia)",
       "Av. Pres. Juan Domingo Perón 26399, Merlo, Bs. As.", "Merlo", "Buenos Aires",
       [_ef("IMSA, Merlo, Buenos Aires, Argentina"),
        _e("Avenida Presidente Juan Domingo Perón 26399, Merlo, Buenos Aires, Argentina"),
        _a("Merlo, Partido de Merlo, Buenos Aires, Argentina")],
       notas="Operando desde 1947. El documento aclara que la ubicación exacta no fue confirmada por fuente secundaria."),

    _r("IND-ENE-004", "Aluar Aluminio Argentino S.A.I.C.", "Central Hidroeléctrica Futaleufú",
       "ENE", "Generación hidroeléctrica",
       "Generación hidroeléctrica (autoabastecimiento industrial)", "560 MW", "",
       "Futaleufú, Chubut", "Futaleufú", "Chubut",
       [_ef("Central Hidroeléctrica Futaleufú, Chubut, Argentina"),
        _a("Embalse Amutui Quimei, Chubut, Argentina"),
        _a("Trevelin, Chubut, Argentina")],
       tipo="CENTRAL_ENERGETICA",
       notas="Abastece la planta de aluminio primario de Puerto Madryn. OSM no expone la presa ni la casa de máquinas: la coordenada es el embalse Amutui Quimei, referencia gruesa del complejo."),

    _r("IND-ENE-005", "Aluar Aluminio Argentino S.A.I.C.", "Parque Eólico Aluar (PEAL)",
       "ENE", "Generación eólica", "Generación eólica",
       "246 MW actuales, proyectado a 582 MW (119 aerogeneradores)", "",
       "Puerto Madryn, Chubut", "Puerto Madryn", "Chubut",
       [_ef("Parque Eólico Aluar, Chubut, Argentina"),
        _ef("Parque Eólico Aluar, Puerto Madryn, Chubut, Argentina"),
        _a("Puerto Madryn, Chubut, Argentina")],
       tipo="CENTRAL_ENERGETICA"),

    _r("IND-ENE-006", "Cementos Avellaneda / YPF Luz", "Parque Eólico Cementos Avellaneda",
       "ENE", "Generación eólica",
       "Generación eólica (autoabastecimiento de planta cementera)",
       "63 MW (9 aerogeneradores Nordex Delta 7MW), factor de capacidad 47%", "",
       "Olavarría, Bs. As. (predio de la cementera, 450 ha)", "Olavarría", "Buenos Aires",
       [_ef("Parque Eólico Cementos Avellaneda, Olavarría, Buenos Aires, Argentina"),
        _a("Olavarría, Buenos Aires, Argentina")],
       tipo="CENTRAL_ENERGETICA"),
]


__all__ = ["REGISTROS", "CATEGORIAS", "CATEGORIA_SLUG", "SIN_DATO"]
